## **UNION DE ARCHIVOS PERSONAS  2018**

In [ ]:
import pandas as pd

In [ ]:
# IMPORTAR ARCHIVOS PERSONAS 2018
df1 = pd.read_csv('/content/CensoPersonas2018_CategoriaAnt.csv')
df2 = pd.read_csv('/content/CensoPersonas2018_CategoriaCun.csv')

In [ ]:
df1.shape

(5974788, 8)

In [ ]:
df2.shape

(2792877, 8)

In [ ]:
df1.shape[0] + df2.shape[0]

8767665

In [ ]:
# Concatenar los DataFrame (Unión vertical)
df_resultado = pd.concat([df1, df2], ignore_index=True)

df_resultado.shape

(8767665, 8)

## **UNION DE ARCHIVOS PERSONAS  2005**

In [ ]:
import pandas as pd

In [ ]:
# IMPORTAR ARCHIVOS PERSONAS 2018
df1 = pd.read_csv('/content/CensoPersonas2005_CategoriaAnt.csv')
df2 = pd.read_csv('/content/CensoPersonas2005_CategoriaCun.csv')

In [ ]:
df1.shape

(1065076, 9)

In [ ]:
df2.shape

(742229, 9)

In [ ]:
df1.shape[0] + df2.shape[0]

1807305

In [ ]:
# Concatenar los DataFrame (Unión vertical)
df_resultado = pd.concat([df1, df2], ignore_index=True)

df_resultado.shape

(1807305, 9)

In [ ]:
df_resultado.head()

,LLAVE_VIVP_N,LLAVE_PER_N,SEXO_CATEGORIA,EDAD_RANGO_CATEGORIA,ALFABETA_CATEGORIA,EDUCACION_NIVEL_EDUCATIVO_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
0,2000000100010001,2000000100010001010001,1 Hombre,6 de 25 A 29 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
1,2000000100010001,2000000100010001010002,1 Hombre,3 de 10 A 14 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
2,2000000100010001,2000000100010001010003,2 Mujer,3 de 10 A 14 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
3,2000000100010001,2000000100010001010004,1 Hombre,3 de 10 A 14 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
4,2000000100010001,2000000100010001010005,1 Hombre,2 de 05 A 09 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN

In [ ]:
df_resultado.tail()

,LLAVE_VIVP_N,LLAVE_PER_N,SEXO_CATEGORIA,EDAD_RANGO_CATEGORIA,ALFABETA_CATEGORIA,EDUCACION_NIVEL_EDUCATIVO_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
1807300,2013228515050002,2013228515050002010004,1 Hombre,5 de 20 A 24 Años,1 SI,99 No Informa,2005,Cundinamarca,ZIPAQUIRA
1807301,2013228515090002,2013228515090002010001,1 Hombre,7 de 30 A 34 Años,1 SI,99 No Informa,2005,Cundinamarca,ZIPAQUIRA
1807302,2013228515090002,2013228515090002010002,2 Mujer,7 de 30 A 34 Años,1 SI,99 No Informa,2005,Cundinamarca,ZIPAQUIRA
1807303,2013228515090002,2013228515090002010003,2 Mujer,3 de 10 A 14 Años,1 SI,6 Normalista,2005,Cundinamarca,ZIPAQUIRA
1807304,2013228515090002,2013228515090002010004,1 Hombre,3 de 10 A 14 Años,1 SI,8 Universitario,2005,Cundinamarca,ZIPAQUIRA

In [ ]:
df_resultado.to_csv('PERSONAS_2005_CAT.csv', index=False)

## **UNION DE ARCHIVOS VIVIENDA 2005**

In [ ]:
import pandas as pd

In [ ]:
# IMPORTAR ARCHIVOS VIVIENDA 2005
df1 = pd.read_csv('/content/CensoVivienda2005_CategoriaAnt.csv')
df2 = pd.read_csv('/content/CensoVivienda2005_CategoriaCun.csv')

In [ ]:
df1.shape

(272956, 7)

In [ ]:
df2.shape

(194775, 7)

In [ ]:
df1.shape[0] + df2.shape[0]

467731

In [ ]:
# Concatenar los DataFrame (Unión vertical)
df_resultado = pd.concat([df1, df2], ignore_index=True)

df_resultado.shape

(467731, 7)

In [ ]:
df_resultado.head()

,LLAVE_VIV_N,TIPO_VIVIENDA_CATEGORIA,TIPO_PAREDES_CATEGORIA,TIPO_ENERGIA_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
0,2000000100010001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
1,2000000100020001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
2,2000000100030001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
3,2000000100040001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
4,2000000100050001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN

In [ ]:
df_resultado.tail()

,LLAVE_VIV_N,TIPO_VIVIENDA_CATEGORIA,TIPO_PAREDES_CATEGORIA,TIPO_ENERGIA_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
467726,2013228515020001,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA
467727,2013228515040003,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA
467728,2013228515050001,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA
467729,2013228515050002,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA
467730,2013228515090002,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA

In [ ]:
df_resultado.to_csv('PERSONAS_2005_CAT.csv', index=False)

## **UNION DE ARCHIVOS VIVIENDA 2018**

In [21]:
import pandas as pd

In [23]:
# IMPORTAR ARCHIVOS VIVIENDA 2005
df1 = pd.read_csv('/content/CensoVivienda2018_CategoriaAnt.csv')
df2 = pd.read_csv('/content/CensoVivienda2018_CategoriaCun.csv')

In [24]:
df1.shape

(2324080, 7)

In [25]:
df2.shape

(1124818, 7)

In [26]:
df1.shape[0] + df2.shape[0]

3448898

In [27]:
# Concatenar los DataFrame (Unión vertical)
df_resultado = pd.concat([df1, df2], ignore_index=True)

df_resultado.shape

(3448898, 7)

In [28]:
df_resultado.head()

,COD_ENCUESTAS,TIPO_VIVIENDA_CATEGORIA,TIPO_PAREDES_CATEGORIA,TIPO_ENERGIA_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
0,3646,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Antioquia,MEDELLIN
1,3649,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Antioquia,MEDELLIN
2,3658,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Antioquia,MEDELLIN
3,3662,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Antioquia,MEDELLIN
4,3666,2 Apartamento,"8 Materiales de deshecho (Zinc, tela, carton, ...",1 SI,2018,Antioquia,MEDELLIN

In [29]:
df_resultado.tail()

,COD_ENCUESTAS,TIPO_VIVIENDA_CATEGORIA,TIPO_PAREDES_CATEGORIA,TIPO_ENERGIA_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
3448893,900539368,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA
3448894,900780632,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA
3448895,900830786,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA
3448896,900832787,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA
3448897,901607162,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA

In [30]:
df_resultado.to_csv('VIVIENDA_2018_CAT.csv', index=False)