## **UNION DATAFRAMES 2005 CON 2015 Y AGRUPACION**

## **1. VIVIENDA**

In [ ]:
# IMPORTAR ARCHIVOS PERSONAS 2018
df1 = pd.read_csv('/content/VIVIENDA_2005_CAT.csv')
df2 = pd.read_csv('/content/VIVIENDA_2018_CAT.csv')

In [ ]:
df1

,LLAVE_VIV_N,TIPO_VIVIENDA_CATEGORIA,TIPO_PAREDES_CATEGORIA,TIPO_ENERGIA_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
0,2000000100010001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
1,2000000100020001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
2,2000000100030001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
3,2000000100040001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
4,2000000100050001,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Antioquia,MEDELLIN
...,...,...,...,...,...,...,...
467726,2013228515020001,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA
467727,2013228515040003,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA
467728,2013228515050001,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA
467729,2013228515050002,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA
467730,2013228515090002,3 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida",1 SI,2005,Cundinamarca,ZIPAQUIRA

In [ ]:
df2

,COD_ENCUESTAS,TIPO_VIVIENDA_CATEGORIA,TIPO_PAREDES_CATEGORIA,TIPO_ENERGIA_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
0,3646,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Antioquia,MEDELLIN
1,3649,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Antioquia,MEDELLIN
2,3658,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Antioquia,MEDELLIN
3,3662,1 Casa,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Antioquia,MEDELLIN
4,3666,2 Apartamento,"8 Materiales de deshecho (Zinc, tela, carton, ...",1 SI,2018,Antioquia,MEDELLIN
...,...,...,...,...,...,...,...
3448893,900539368,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA
3448894,900780632,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA
3448895,900830786,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA
3448896,900832787,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA
3448897,901607162,2 Apartamento,"1 Bloque, ladrillo, piedra, madera pulida 2 Co...",1 SI,2018,Cundinamarca,ZIPAQUIRA

In [ ]:
# ELIMINIAR CAMPOS NO COMUNES
df1 = df1.drop(columns=['LLAVE_VIV_N'])
df2 = df2.drop(columns=['COD_ENCUESTAS'])

In [ ]:
#CANTIDAD
df1.shape

(467731, 6)

In [ ]:
#CANTIDAD
df2.shape

(3448898, 6)

In [ ]:
# SUMA TOTAL DE REGISTROS
df1.shape[0] + df2.shape[0]

3916629

In [ ]:
# Concatenar los DataFrame (Unión vertical)
df_resultado = pd.concat([df1, df2], ignore_index=True)

df_resultado.shape

(3916629, 6)

In [ ]:
df_resultado.to_csv('VIVIENDAS.csv', index=False)

In [ ]:
import pandas as pd
df_resultado = pd.read_csv('/content/VIVIENDAS.csv')

In [ ]:
# AGRUPAR
filtered_data=df_resultado.groupby(['TIPO_VIVIENDA_CATEGORIA', 'DEPARTAMENTO_NOMBRE', 'AÑO']).size().reset_index(name='count')

In [ ]:
filtered_data

,TIPO_VIVIENDA_CATEGORIA,DEPARTAMENTO_NOMBRE,AÑO,count
0,1 Casa,Antioquia,2005,208612
1,1 Casa,Antioquia,2018,1218936
2,1 Casa,Cundinamarca,2005,170142
3,1 Casa,Cundinamarca,2018,710791
4,2 Apartamento,Antioquia,2018,1037197
5,2 Apartamento,Cundinamarca,2018,363997
6,2 Casa indigena,Antioquia,2005,1875
7,2 Casa indigena,Cundinamarca,2005,209
8,3 Apartamento,Antioquia,2005,51068
9,3 Apartamento,Cundinamarca,2005,20331
10,3 Tipo cuarto,Antioquia,2018,60041
11,3 Tipo cuarto,Cundinamarca,2018,47703
12,4 Tipo cuarto,Antioquia,2005,10807
13,4 Tipo cuarto,Cundinamarca,2005,3478
14,4 Vivienda tradicional Indigena 5 Vivienda tra...,Antioquia,2018,3954
15,4 Vivienda tradicional Indigena 5 Vivienda tra...,Cundinamarca,2018,286
16,5 Otro tipo de vivienda,Antioquia,2005,594
17,5 Otro tipo de vivienda,Cundinamarca,2005,615
18,"6 Otro (contenedor, carpa, embarcacion, vagon,...",Antioquia,2018,3952
19,"6 Otro (contenedor, carpa, embarcacion, vagon,...",Cundinamarca,2018,2041

In [ ]:
#EXPORTAR
filtered_data.to_csv('VIVIENDAS_AGRUPADAS.csv', index=False)

## **2. PERSONAS**

### **2.1 NIVEL EDUCATIVO**

In [ ]:
# IMPORTAR ARCHIVOS PERSONAS 2018
df1 = pd.read_csv('/content/PERSONAS_2005_CAT.csv')
df2 = pd.read_csv('/content/PERSONAS_2018_CAT.csv')

In [ ]:
df1

,LLAVE_VIVP_N,LLAVE_PER_N,SEXO_CATEGORIA,EDAD_RANGO_CATEGORIA,ALFABETA_CATEGORIA,EDUCACION_NIVEL_EDUCATIVO_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
0,2000000100010001,2000000100010001010001,1 Hombre,6 de 25 A 29 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
1,2000000100010001,2000000100010001010002,1 Hombre,3 de 10 A 14 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
2,2000000100010001,2000000100010001010003,2 Mujer,3 de 10 A 14 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
3,2000000100010001,2000000100010001010004,1 Hombre,3 de 10 A 14 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
4,2000000100010001,2000000100010001010005,1 Hombre,2 de 05 A 09 Años,2 NO,99 No Informa,2005,Antioquia,MEDELLIN
...,...,...,...,...,...,...,...,...,...
1807300,2013228515050002,2013228515050002010004,1 Hombre,5 de 20 A 24 Años,1 SI,99 No Informa,2005,Cundinamarca,ZIPAQUIRA
1807301,2013228515090002,2013228515090002010001,1 Hombre,7 de 30 A 34 Años,1 SI,99 No Informa,2005,Cundinamarca,ZIPAQUIRA
1807302,2013228515090002,2013228515090002010002,2 Mujer,7 de 30 A 34 Años,1 SI,99 No Informa,2005,Cundinamarca,ZIPAQUIRA
1807303,2013228515090002,2013228515090002010003,2 Mujer,3 de 10 A 14 Años,1 SI,6 Normalista,2005,Cundinamarca,ZIPAQUIRA
1807304,2013228515090002,2013228515090002010004,1 Hombre,3 de 10 A 14 Años,1 SI,8 Universitario,2005,Cundinamarca,ZIPAQUIRA

In [ ]:
df2

,COD_ENCUESTAS,SEXO_CATEGORIA,EDAD_RANGO_CATEGORIA,ALFABETA_CATEGORIA,EDUCACION_NIVEL_EDUCATIVO_CATEGORIA,AÑO,DEPARTAMENTO_NOMBRE,NOMBRE_MUNICIPIO
0,3626,1 Hombre,5 de 20 A 24 Años,1 SI,4 Media academica o clasica,2018,Antioquia,MEDELLIN
1,3626,2 Mujer,11 de 50 A 54 Años,1 SI,4 Media academica o clasica,2018,Antioquia,MEDELLIN
2,3626,2 Mujer,7 de 30 A 34 Años,1 SI,7 Técnica profesional o Tecnológica,2018,Antioquia,MEDELLIN
3,3626,2 Mujer,1 de 00 A 04 Años,9 No Informa,99 No Informa,2018,Antioquia,MEDELLIN
4,3626,1 Hombre,11 de 50 A 54 Años,1 SI,4 Media academica o clasica,2018,Antioquia,MEDELLIN
...,...,...,...,...,...,...,...,...
8767660,902341000,1 Hombre,16 de 75 A 79 Años,1 SI,2 Básica primaria,2018,Cundinamarca,ZIPAQUIRA
8767661,902341176,1 Hombre,10 de 45 A 49 Años,9 No Informa,99 No Informa,2018,Cundinamarca,ZIPAQUIRA
8767662,902341176,2 Mujer,14 de 65 A 69 Años,9 No Informa,99 No Informa,2018,Cundinamarca,ZIPAQUIRA
8767663,902341176,1 Hombre,2 de 05 A 09 Años,9 No Informa,99 No Informa,2018,Cundinamarca,ZIPAQUIRA
8767664,902341176,1 Hombre,2 de 05 A 09 Años,9 No Informa,99 No Informa,2018,Cundinamarca,ZIPAQUIRA

In [ ]:
df1 = df1.drop(columns=['LLAVE_VIVP_N'])
df1 = df1.drop(columns=['LLAVE_PER_N'])

df2 = df2.drop(columns=['COD_ENCUESTAS'])

In [ ]:
df1.shape

(1807305, 7)

In [ ]:
df2.shape

(8767665, 7)

In [ ]:
df1.shape[0] + df2.shape[0]

10574970

In [ ]:
# Concatenar los DataFrame (Unión vertical)
df_resultado = pd.concat([df1, df2], ignore_index=True)

df_resultado.shape

(10574970, 7)

In [ ]:
df_resultado.to_csv('PERSONAS.csv', index=False)

In [ ]:
import pandas as pd
df_resultado = pd.read_csv('/content/VIVIENDAS.csv')

In [ ]:
filtered_data=df_resultado.groupby(['EDUCACION_NIVEL_EDUCATIVO_CATEGORIA', 'DEPARTAMENTO_NOMBRE', 'AÑO']).size().reset_index(name='count')

In [ ]:
filtered_data

       EDUCACION_NIVEL_EDUCATIVO_CATEGORIA DEPARTAMENTO_NOMBRE   AÑO    count
0                             1 Preescolar           Antioquia  2005    15301
1                             1 Preescolar           Antioquia  2018   110875
2                             1 Preescolar        Cundinamarca  2005     7375
3                             1 Preescolar        Cundinamarca  2018    59855
4                        2 Básica primaria           Antioquia  2005    52805
5                        2 Básica primaria           Antioquia  2018  1619424
6                        2 Básica primaria        Cundinamarca  2005    32423
7                        2 Básica primaria        Cundinamarca  2018   784723
8                      3 Básica secundaria           Antioquia  2005    54726
9                      3 Básica secundaria           Antioquia  2018   952850
10                     3 Básica secundaria        Cundinamarca  2005    37017
11                     3 Básica secundaria        Cundinamarca  2018   427151
12             4 Media academica o clasica           Antioquia  2005      280
13             4 Media academica o clasica           Antioquia  2018  1352437
14             4 Media academica o clasica        Cundinamarca  2005      124
15             4 Media academica o clasica        Cundinamarca  2018   620921
16                         5 Media tecnica           Antioquia  2005    50979
17                         5 Media tecnica           Antioquia  2018    69003
18                         5 Media tecnica        Cundinamarca  2005    36986
19                         5 Media tecnica        Cundinamarca  2018    50703
20                            6 Normalista           Antioquia  2005    25619
21                            6 Normalista           Antioquia  2018    28510
22                            6 Normalista        Cundinamarca  2005    20383
23                            6 Normalista        Cundinamarca  2018    10407
24     7 Técnica profesional o Tecnológica           Antioquia  2005     4371
25     7 Técnica profesional o Tecnológica           Antioquia  2018   527587
26     7 Técnica profesional o Tecnológica        Cundinamarca  2005     3280
27     7 Técnica profesional o Tecnológica        Cundinamarca  2018   227404
28                         8 Universitario           Antioquia  2005    32090
29                         8 Universitario           Antioquia  2018   523255
30                         8 Universitario        Cundinamarca  2005    27707
31                         8 Universitario        Cundinamarca  2018   255370
32  9 Especialización, maestría, doctorado           Antioquia  2005     4944
33  9 Especialización, maestría, doctorado           Antioquia  2018   146248
34  9 Especialización, maestría, doctorado        Cundinamarca  2005     4851
35  9 Especialización, maestría, doctorado        Cundinamarca  2018    57050
36                           99 No Informa           Antioquia  2005   823961
37                           99 No Informa           Antioquia  2018   644599
38                           99 No Informa        Cundinamarca  2005   572083
39                           99 No Informa        Cundinamarca  2018   299293

In [ ]:
filtered_data.shape

(40, 4)

In [ ]:
filtered_data.to_csv('ESTUDIOS.csv', index=False)

### **2.2 ALFABETA**

In [ ]:
filtered_data=df_resultado.groupby(['ALFABETA_CATEGORIA', 'DEPARTAMENTO_NOMBRE', 'AÑO']).size().reset_index(name='count')

In [ ]:
filtered_data.shape

(12, 4)

In [ ]:
filtered_data.to_csv('ALFABETA.csv', index=False)

### **2.2 SEXO**

In [ ]:
filtered_data=df_resultado.groupby(['SEXO_CATEGORIA', 'DEPARTAMENTO_NOMBRE', 'AÑO']).size().reset_index(name='count')

In [ ]:
filtered_data.shape

(8, 4)

In [ ]:
filtered_data

  SEXO_CATEGORIA DEPARTAMENTO_NOMBRE   AÑO    count
0       1 Hombre           Antioquia  2005   532854
1       1 Hombre           Antioquia  2018  2885383
2       1 Hombre        Cundinamarca  2005   378434
3       1 Hombre        Cundinamarca  2018  1379858
4        2 Mujer           Antioquia  2005   532222
5        2 Mujer           Antioquia  2018  3089405
6        2 Mujer        Cundinamarca  2005   363795
7        2 Mujer        Cundinamarca  2018  1413019

In [ ]:
filtered_data.to_csv('SEXO.csv', index=False)